export const actions = {
    profile: {
        DATA_USER_FETCHING: 'PROFILE_DATA_FETCHING',
        DATA_USER_FETCHED: 'PROFILE_DATA_FETCHED',
        DATA_USER_ERROR: 'PROFILE_DATA_FETCH_ERROR',
        IMAGE_UPLOADED: 'PROFILE_IMAGE_UPLOADED',
        USER_DATA_EDITED: 'PROFILE_DATA_EDITED',
    },
    post: {
        DATA_FETCHING: 'POST_DATA_FETCHING',
        DATA_FETCHED: 'POST_DATA_FETCHED',
        DATA_ERROR: 'POST_DATA_FETCH_ERROR',
        POST_EDITED: 'POST_DATA_EDITED',
        POST_DELETED: 'POST_DATA_DELETED',
        POST_CREATED: 'POST_DATA_CREATED',
    },
};
